name: myflask
version: 0.0.1
summary: Myflask
description: |
  Myflask

base: core18

grade: stable
confinement: strict


apps:
  myflask:
    command: python3 $SNAP/application.py
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  myflask:
    plugin: dump
    source: .

    override-pull: |
      snapcraftctl pull
      echo "PULLSTEPCOMPLETE" > $SNAPCRAFT_PART_INSTALL/RATS_pull.txt

    override-build: |
      snapcraftctl build
      echo "BUILDSTEPCOMPLETE" > $SNAPCRAFT_PART_BUILD/RATS_build.txt

    build-packages:
      - python3-pip
    stage-packages:
      - python3-pip
      - python3-all
    override-build: |
      snapcraftctl build
      pip3 install flask

  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/
