name: myflask
version: 0.0.1
summary: Myflask
description: |
  Myflask

base: core18

grade: stable
confinement: strict


apps:
  myflask:
    command: python3 $SNAP/application.py
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  myflask:
    source: .
    plugin: dump
    build-packages:
      - python3-pip
    stage-packages:
      - python3-pip
      - python3-all
    override-build: |
      snapcraftctl build
      pip3 install flask
